# Generated by Django 3.2.7 on 2021-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_session',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
