# Generated by Django 3.2.7 on 2021-10-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usermodel_user_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_session',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
